// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Unravel.Infrastructure.Persistence;

#nullable disable

namespace Unravel.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260427005202_AddGamification")]
    partial class AddGamification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Unravel.Domain.Entities.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsExclusive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_exclusive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_badge");

                    b.ToTable("badge", (string)null);
                });

            modelBuilder.Entity("Unravel.Domain.Entities.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoinsReward")
                        .HasColumnType("integer")
                        .HasColumnName("coins_reward");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDailyChallenge")
                        .HasColumnType("boolean")
                        .HasColumnName("is_daily_challenge");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("TrailId")
                        .HasColumnType("integer")
                        .HasColumnName("trail_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("XpReward")
                        .HasColumnType("integer")
                        .HasColumnName("xp_reward");

                    b.HasKey("Id")
                        .HasName("pk_challenge");

                    b.HasIndex("TrailId")
                        .HasDatabaseName("ix_challenge_trail_id");

                    b.ToTable("challenge", (string)null);
                });

            modelBuilder.Entity("Unravel.Domain.Entities.ChallengeOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("integer")
                        .HasColumnName("challenge_id");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_challenge_option");

                    b.HasIndex("ChallengeId")
                        .HasDatabaseName("ix_challenge_option_challenge_id");

                    b.ToTable("challenge_option", (string)null);
                });

            modelBuilder.Entity("Unravel.Domain.Entities.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("TrailId")
                        .HasColumnType("integer")
                        .HasColumnName("trail_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_content");

                    b.HasIndex("TrailId")
                        .HasDatabaseName("ix_content_trail_id");

                    b.ToTable("content", (string)null);
                });

            modelBuilder.Entity("Unravel.Domain.Entities.NaviCosmetic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("asset_slug");

                    b.Property<int>("CoinPrice")
                        .HasColumnType("integer")
                        .HasColumnName("coin_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsExclusive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_exclusive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer")
                        .HasColumnName("rarity");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_navi_cosmetic");

                    b.ToTable("navi_cosmetic", (string)null);
                });

            modelBuilder.Entity("Unravel.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_token_user_id");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("Unravel.Domain.Entities.Trail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("accent_color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_trail");

                    b.ToTable("trail", (string)null);
                });

            modelBuilder.Entity("Unravel.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ActiveCosmeticId")
                        .HasColumnType("integer")
                        .HasColumnName("active_cosmetic_id");

                    b.Property<string>("ActiveTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("active_title");

                    b.Property<int>("Coins")
                        .HasColumnType("integer")
                        .HasColumnName("coins");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastActivityDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_date");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_date");

                    b.Property<int>("Lives")
                        .HasColumnType("integer")
                        .HasColumnName("lives");

                    b.Property<int>("LoginCycleDay")
                        .HasColumnType("integer")
                        .HasColumnName("login_cycle_day");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer")
                        .HasColumnName("longest_streak");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Stars")
                        .HasColumnType("integer")
                        .HasColumnName("stars");

                    b.Property<int>("StreakDays")
                        .HasColumnType("integer")
                        .HasColumnName("streak_days");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Xp")
                        .HasColumnType("integer")
                        .HasColumnName("xp");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Unravel.Domain.Entities.UserBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BadgeId")
                        .HasColumnType("integer")
                        .HasColumnName("badge_id");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("earned_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_badge");

                    b.HasIndex("BadgeId")
                        .HasDatabaseName("ix_user_badge_badge_id");

                    b.HasIndex("UserId", "BadgeId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_badge_user_id_badge_id");

                    b.ToTable("user_badge", (string)null);
                });

            modelBuilder.Entity("Unravel.Domain.Entities.UserChallenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvgResponseTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("avg_response_time_ms");

                    b.Property<int>("ChallengeId")
                        .HasColumnType("integer")
                        .HasColumnName("challenge_id");

                    b.Property<int>("CoinsEarned")
                        .HasColumnType("integer")
                        .HasColumnName("coins_earned");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("correct_answers");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<bool>("IsPerfect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_perfect");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("total_questions");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("XpEarned")
                        .HasColumnType("integer")
                        .HasColumnName("xp_earned");

                    b.HasKey("Id")
                        .HasName("pk_user_challenge");

                    b.HasIndex("ChallengeId")
                        .HasDatabaseName("ix_user_challenge_challenge_id");

                    b.HasIndex("UserId", "ChallengeId", "StartedAt")
                        .HasDatabaseName("ix_user_challenge_user_id_challenge_id_started_at");

                    b.ToTable("user_challenge", (string)null);
                });

            modelBuilder.Entity("Unravel.Domain.Entities.UserContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("ContentId")
                        .HasColumnType("integer")
                        .HasColumnName("content_id");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_content");

                    b.HasIndex("ContentId")
                        .HasDatabaseName("ix_user_content_content_id");

                    b.HasIndex("UserId", "ContentId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_content_user_id_content_id");

                    b.ToTable("user_content", (string)null);
                });

            modelBuilder.Entity("Unravel.Domain.Entities.UserCosmetic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired_at");

                    b.Property<int>("CosmeticId")
                        .HasColumnType("integer")
                        .HasColumnName("cosmetic_id");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("boolean")
                        .HasColumnName("is_equipped");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_cosmetic");

                    b.HasIndex("CosmeticId")
                        .HasDatabaseName("ix_user_cosmetic_cosmetic_id");

                    b.HasIndex("UserId", "CosmeticId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_cosmetic_user_id_cosmetic_id");

                    b.ToTable("user_cosmetic", (string)null);
                });

            modelBuilder.Entity("Unravel.Domain.Entities.UserTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<int>("TrailId")
                        .HasColumnType("integer")
                        .HasColumnName("trail_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_trail");

                    b.HasIndex("TrailId")
                        .HasDatabaseName("ix_user_trail_trail_id");

                    b.HasIndex("UserId", "TrailId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_trail_user_id_trail_id");

                    b.ToTable("user_trail", (string)null);
                });

            modelBuilder.Entity("Unravel.Domain.Entities.Challenge", b =>
                {
                    b.HasOne("Unravel.Domain.Entities.Trail", "Trail")
                        .WithMany()
                        .HasForeignKey("TrailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_challenge_trail_trail_id");

                    b.Navigation("Trail");
                });

            modelBuilder.Entity("Unravel.Domain.Entities.ChallengeOption", b =>
                {
                    b.HasOne("Unravel.Domain.Entities.Challenge", "Challenge")
                        .WithMany("Options")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_challenge_option_challenge_challenge_id");

                    b.Navigation("Challenge");
                });

            modelBuilder.Entity("Unravel.Domain.Entities.Content", b =>
                {
                    b.HasOne("Unravel.Domain.Entities.Trail", "Trail")
                        .WithMany("Contents")
                        .HasForeignKey("TrailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_content_trail_trail_id");

                    b.Navigation("Trail");
                });

            modelBuilder.Entity("Unravel.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Unravel.Domain.Entities.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_user_user_id");
                });

            modelBuilder.Entity("Unravel.Domain.Entities.User", b =>
                {
                    b.OwnsOne("Unravel.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_user_email");

                            b1.ToTable("user");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_user_user_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("Unravel.Domain.Entities.UserBadge", b =>
                {
                    b.HasOne("Unravel.Domain.Entities.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_badge_badge_badge_id");

                    b.HasOne("Unravel.Domain.Entities.User", "User")
                        .WithMany("Badges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_badge_user_user_id");

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Unravel.Domain.Entities.UserChallenge", b =>
                {
                    b.HasOne("Unravel.Domain.Entities.Challenge", "Challenge")
                        .WithMany("UserAttempts")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_challenge_challenge_challenge_id");

                    b.HasOne("Unravel.Domain.Entities.User", "User")
                        .WithMany("ChallengeAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_challenge_user_user_id");

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Unravel.Domain.Entities.UserContent", b =>
                {
                    b.HasOne("Unravel.Domain.Entities.Content", "Content")
                        .WithMany("UserContents")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_content_content_content_id");

                    b.HasOne("Unravel.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_content_user_user_id");

                    b.Navigation("Content");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Unravel.Domain.Entities.UserCosmetic", b =>
                {
                    b.HasOne("Unravel.Domain.Entities.NaviCosmetic", "Cosmetic")
                        .WithMany("UserCosmetics")
                        .HasForeignKey("CosmeticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_cosmetic_navi_cosmetic_cosmetic_id");

                    b.HasOne("Unravel.Domain.Entities.User", "User")
                        .WithMany("Cosmetics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_cosmetic_user_user_id");

                    b.Navigation("Cosmetic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Unravel.Domain.Entities.UserTrail", b =>
                {
                    b.HasOne("Unravel.Domain.Entities.Trail", "Trail")
                        .WithMany("UserTrails")
                        .HasForeignKey("TrailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_trail_trail_trail_id");

                    b.HasOne("Unravel.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_trail_user_user_id");

                    b.Navigation("Trail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Unravel.Domain.Entities.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("Unravel.Domain.Entities.Challenge", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("UserAttempts");
                });

            modelBuilder.Entity("Unravel.Domain.Entities.Content", b =>
                {
                    b.Navigation("UserContents");
                });

            modelBuilder.Entity("Unravel.Domain.Entities.NaviCosmetic", b =>
                {
                    b.Navigation("UserCosmetics");
                });

            modelBuilder.Entity("Unravel.Domain.Entities.Trail", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("UserTrails");
                });

            modelBuilder.Entity("Unravel.Domain.Entities.User", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("ChallengeAttempts");

                    b.Navigation("Cosmetics");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
